### PR TITLE
Faster `merge_sorted` using binary merge.

### PR DESCRIPTION
**Pull request by eriknw**
This is 2-3x faster than the fast `toolz` version, and 4-5x faster than the previous `cytoolz` version.  Hooray!

### CODE REVIEW

**Comment by MSeifert04** [comment]
Hi @eriknw I hope you don't mind if I ask.

But you mentioned the performance, so, do you know how does the (new) implementation compare to `sorted(chain(*iterables))` or `heapq.merge(*iterables)`?

**Comment by eriknw** [comment]
Excellent suggestion!  This should be very informative.  Give me a few minutes to run my benchmarks.  Care to share your expectations?

Also, I think I need to look more closely at https://github.com/MSeifert04/iutils_benchmarks .  Are there any obvious functions that we should optimize?

**Comment by eriknw** [comment]
Here is a table of benchmarks comparing the latest `merge_sorted` from `toolz` and `cytoolz` with the two suggestions from @MSeifert04, `sorted(chain(*iterables))` and `heapq.merge(*iterables)` in Python 2.7.  Code for the benchmarks is below.  There are probably both too many and too few benchmarks here--we don't need as many as we do to capture the trends that these show, and we are probably missing variety.

`cytoolz` is the clear winner and `heapq` the clear loser to my eyes.  I think `toolz` does pretty well for being pure Python.  Note that `sorted(chain(...))` is useful to compare to, but it has different behavior.  Unlike the other methods that perform the merge lazily, it performs the merge greedily in memory.

Short summary: `cytoolz` does better relative to others (especially `chain` and `heapq`) the fewer the iterables and the longer the iterables.

**Relative time:**

|  __Bench__ \ __Func__ | __chain__ | __cytoolz__ | __heapq__ | __toolz__ |
| ---------------------:|:---------:|:-----------:|:---------:|:---------:|
|     __merge_sorted0__ |   *1.54*  |    __1__    |    7.35   |    2.08   |
|   __merge_sorted0_4__ |   *1.31*  |    __1__    |    5.35   |    2.15   |
|   __merge_sorted0_8__ |   *1.13*  |    __1__    |    3.89   |    1.94   |
|  __merge_sorted0_16__ |   *1.21*  |    __1__    |    3.59   |    1.99   |
|     __merge_sorted1__ |   *1.48*  |    __1__    |    7.98   |    2.27   |
|   __merge_sorted1_4__ |   *1.18*  |    __1__    |    6.57   |    2.44   |
|   __merge_sorted1_8__ |   *1.14*  |    __1__    |    4.84   |    2.28   |
|  __merge_sorted1_16__ |   *1.07*  |    __1__    |    3.82   |    2.07   |
|     __merge_sorted2__ |   *1.48*  |    __1__    |    7.97   |    2.28   |
|   __merge_sorted2_4__ |   *1.19*  |    __1__    |    6.63   |    2.47   |
|   __merge_sorted2_8__ |   *1.07*  |    __1__    |    5.72   |    2.58   |
|  __merge_sorted2_16__ |   *1.07*  |    __1__    |    4.54   |    2.34   |
|     __merge_sorted3__ |   *1.5*   |    __1__    |     8     |    2.27   |
|   __merge_sorted3_4__ |   *1.18*  |    __1__    |    6.78   |    2.44   |
|   __merge_sorted3_8__ |   *1.04*  |    __1__    |    5.78   |    2.59   |
|  __merge_sorted3_16__ |   __1__   |    *1.03*   |    5.33   |    2.66   |
|     __merge_sorted4__ |   *1.48*  |    __1__    |    8.06   |    2.28   |
|   __merge_sorted4_4__ |   *1.19*  |    __1__    |    6.74   |    2.48   |
|   __merge_sorted4_8__ |   *1.04*  |    __1__    |    5.75   |    2.57   |
|  __merge_sorted4_16__ |   __1__   |    *1.04*   |    5.34   |    2.66   |
|     __merge_sorted5__ |   *1.47*  |    __1__    |    8.03   |    2.3    |
|   __merge_sorted5_4__ |   *1.17*  |    __1__    |    6.58   |    2.43   |
|   __merge_sorted5_8__ |   *1.05*  |    __1__    |    5.75   |    2.56   |
|  __merge_sorted5_16__ |   __1__   |    *1.03*   |    5.29   |    2.64   |
|     __merge_sorted6__ |   *1.5*   |    __1__    |    8.14   |    2.3    |
|   __merge_sorted6_4__ |   *1.18*  |    __1__    |    6.64   |    2.45   |
|   __merge_sorted6_8__ |   *1.04*  |    __1__    |    5.75   |    2.56   |
|  __merge_sorted6_16__ |   __1__   |    *1.04*   |    5.32   |    2.66   |
|     __merge_sorted7__ |   *1.6*   |    __1__    |    8.91   |    2.44   |
|   __merge_sorted7_4__ |   *1.16*  |    __1__    |    6.73   |    2.48   |
|   __merge_sorted7_8__ |   *1.02*  |    __1__    |    5.72   |    2.56   |
|  __merge_sorted7_16__ |   __1__   |    *1.05*   |    5.44   |    2.71   |
|     __merge_sorted8__ |   *1.65*  |    __1__    |    9.19   |    2.5    |
|   __merge_sorted8_4__ |   *1.19*  |    __1__    |    7.15   |    2.59   |
|   __merge_sorted8_8__ |   __1__   |    *1.01*   |    5.83   |    2.62   |
|  __merge_sorted8_16__ |   __1__   |    *1.1*    |    5.57   |    2.78   |
|     __merge_sorted9__ |   *1.75*  |    __1__    |    9.21   |    2.54   |
|   __merge_sorted9_4__ |   *1.24*  |    __1__    |    7.44   |    2.69   |
|   __merge_sorted9_8__ |   *1.03*  |    __1__    |    6.17   |    2.71   |
|  __merge_sorted9_16__ |   __1__   |    *1.12*   |    5.69   |    2.87   |
|    __merge_sorted10__ |   *1.77*  |    __1__    |    9.17   |    2.54   |
|  __merge_sorted10_4__ |   *1.26*  |    __1__    |    7.3    |    2.66   |
|  __merge_sorted10_8__ |   *1.05*  |    __1__    |    6.34   |    2.78   |
| __merge_sorted10_16__ |   __1__   |    *1.1*    |    5.83   |    2.89   |
|    __merge_sorted11__ |   *1.68*  |    __1__    |    8.66   |    2.52   |
|  __merge_sorted11_4__ |   *1.24*  |    __1__    |    7.23   |    2.66   |
|  __merge_sorted11_8__ |   *1.07*  |    __1__    |    6.36   |    2.81   |
| __merge_sorted11_16__ |   __1__   |    *1.08*   |    5.92   |    2.92   |
|    __merge_sorted12__ |   *1.96*  |    __1__    |    7.93   |    2.48   |
|  __merge_sorted12_4__ |   *1.45*  |    __1__    |    7.1    |    2.67   |
|  __merge_sorted12_8__ |   *1.19*  |    __1__    |    6.28   |    2.83   |
| __merge_sorted12_16__ |   *1.07*  |    __1__    |    5.53   |    2.78   |
|    __merge_sorted13__ |   *1.5*   |    __1__    |    6.86   |    2.25   |
|  __merge_sorted13_4__ |   *1.21*  |    __1__    |    6.43   |    2.43   |
|  __merge_sorted13_8__ |   __1__   |    *1.02*   |     6     |    2.72   |
| __merge_sorted13_16__ |   __1__   |    *1.05*   |    5.62   |    2.85   |
|    __merge_sorted14__ |   *1.3*   |    __1__    |    6.16   |    2.11   |
|  __merge_sorted14_4__ |   __1__   |    *1.17*   |    6.63   |    2.61   |
|  __merge_sorted14_8__ |   __1__   |    *1.34*   |    7.2    |    3.16   |
| __merge_sorted14_16__ |   __1__   |    *1.43*   |    7.27   |    3.53   |
|    __merge_sorted15__ |   *1.31*  |    __1__    |    5.11   |    2.05   |
|  __merge_sorted15_4__ |   __1__   |    *1.56*   |    7.58   |    3.16   |
|  __merge_sorted15_8__ |   __1__   |    *1.97*   |    9.21   |    4.14   |
| __merge_sorted15_16__ |   __1__   |    *2.22*   |    9.82   |    4.79   |

```python
import random
from cytoolz.utils import consume

random.seed(10)

LS = [
    [sorted(random.random() for _ in range(2**(16-i))) for _ in range(2**1)]
    for i in range(16)
]

def bench_merge_sorted0():
    consume(merge_sorted(*LS[0]))
def bench_merge_sorted1():
    consume(merge_sorted(*LS[1]))
def bench_merge_sorted2():
    consume(merge_sorted(*LS[2]))
def bench_merge_sorted3():
    consume(merge_sorted(*LS[3]))
def bench_merge_sorted4():
    consume(merge_sorted(*LS[4]))
def bench_merge_sorted5():
    consume(merge_sorted(*LS[5]))
def bench_merge_sorted6():
    consume(merge_sorted(*LS[6]))
def bench_merge_sorted7():
    consume(merge_sorted(*LS[7]))
def bench_merge_sorted8():
    consume(merge_sorted(*LS[8]))
def bench_merge_sorted9():
    consume(merge_sorted(*LS[9]))
def bench_merge_sorted10():
    consume(merge_sorted(*LS[10]))
def bench_merge_sorted11():
    consume(merge_sorted(*LS[11]))
def bench_merge_sorted12():
    consume(merge_sorted(*LS[12]))
def bench_merge_sorted13():
    consume(merge_sorted(*LS[13]))
def bench_merge_sorted14():
    consume(merge_sorted(*LS[14]))
def bench_merge_sorted15():
    consume(merge_sorted(*LS[15]))


LS8 = [
    [sorted(random.random() for _ in range(2**(16-i))) for _ in range(2**3)]
    for i in range(16)
]

def bench_merge_sorted0_8():
    consume(merge_sorted(*LS8[0]))
def bench_merge_sorted1_8():
    consume(merge_sorted(*LS8[1]))
def bench_merge_sorted2_8():
    consume(merge_sorted(*LS8[2]))
def bench_merge_sorted3_8():
    consume(merge_sorted(*LS8[3]))
def bench_merge_sorted4_8():
    consume(merge_sorted(*LS8[4]))
def bench_merge_sorted5_8():
    consume(merge_sorted(*LS8[5]))
def bench_merge_sorted6_8():
    consume(merge_sorted(*LS8[6]))
def bench_merge_sorted7_8():
    consume(merge_sorted(*LS8[7]))
def bench_merge_sorted8_8():
    consume(merge_sorted(*LS8[8]))
def bench_merge_sorted9_8():
    consume(merge_sorted(*LS8[9]))
def bench_merge_sorted10_8():
    consume(merge_sorted(*LS8[10]))
def bench_merge_sorted11_8():
    consume(merge_sorted(*LS8[11]))
def bench_merge_sorted12_8():
    consume(merge_sorted(*LS8[12]))
def bench_merge_sorted13_8():
    consume(merge_sorted(*LS8[13]))
def bench_merge_sorted14_8():
    consume(merge_sorted(*LS8[14]))
def bench_merge_sorted15_8():
    consume(merge_sorted(*LS8[15]))


LS4 = [
    [sorted(random.random() for _ in range(2**(16-i))) for _ in range(2**2)]
    for i in range(16)
]

def bench_merge_sorted0_4():
    consume(merge_sorted(*LS4[0]))
def bench_merge_sorted1_4():
    consume(merge_sorted(*LS4[1]))
def bench_merge_sorted2_4():
    consume(merge_sorted(*LS4[2]))
def bench_merge_sorted3_4():
    consume(merge_sorted(*LS4[3]))
def bench_merge_sorted4_4():
    consume(merge_sorted(*LS4[4]))
def bench_merge_sorted5_4():
    consume(merge_sorted(*LS4[5]))
def bench_merge_sorted6_4():
    consume(merge_sorted(*LS4[6]))
def bench_merge_sorted7_4():
    consume(merge_sorted(*LS4[7]))
def bench_merge_sorted8_4():
    consume(merge_sorted(*LS4[8]))
def bench_merge_sorted9_4():
    consume(merge_sorted(*LS4[9]))
def bench_merge_sorted10_4():
    consume(merge_sorted(*LS4[10]))
def bench_merge_sorted11_4():
    consume(merge_sorted(*LS4[11]))
def bench_merge_sorted12_4():
    consume(merge_sorted(*LS4[12]))
def bench_merge_sorted13_4():
    consume(merge_sorted(*LS4[13]))
def bench_merge_sorted14_4():
    consume(merge_sorted(*LS4[14]))
def bench_merge_sorted15_4():
    consume(merge_sorted(*LS4[15]))


LS16 = [
    [sorted(random.random() for _ in range(2**(16-i))) for _ in range(2**4)]
    for i in range(16)
]

def bench_merge_sorted0_16():
    consume(merge_sorted(*LS16[0]))
def bench_merge_sorted1_16():
    consume(merge_sorted(*LS16[1]))
def bench_merge_sorted2_16():
    consume(merge_sorted(*LS16[2]))
def bench_merge_sorted3_16():
    consume(merge_sorted(*LS16[3]))
def bench_merge_sorted4_16():
    consume(merge_sorted(*LS16[4]))
def bench_merge_sorted5_16():
    consume(merge_sorted(*LS16[5]))
def bench_merge_sorted6_16():
    consume(merge_sorted(*LS16[6]))
def bench_merge_sorted7_16():
    consume(merge_sorted(*LS16[7]))
def bench_merge_sorted8_16():
    consume(merge_sorted(*LS16[8]))
def bench_merge_sorted9_16():
    consume(merge_sorted(*LS16[9]))
def bench_merge_sorted10_16():
    consume(merge_sorted(*LS16[10]))
def bench_merge_sorted11_16():
    consume(merge_sorted(*LS16[11]))
def bench_merge_sorted12_16():
    consume(merge_sorted(*LS16[12]))
def bench_merge_sorted13_16():
    consume(merge_sorted(*LS16[13]))
def bench_merge_sorted14_16():
    consume(merge_sorted(*LS16[14]))
def bench_merge_sorted15_16():
    consume(merge_sorted(*LS16[15]))
```

**Comment by MSeifert04** [comment]
I think it's very hard to beat `sorted` because it uses TimSort. TimSort is optimized for the case that blocks are already sorted, so if you have iterables with more than a few elements `sorted` is faster/not much slower. As you noted it's greedy so not fit for direct comparisons.
`heapq` is actually not hard to beat because it's a naive pure python implementation, it uses the C-heapq but on top it's Python with all it's attribute lookups. Also heapq does not support reverse and key before Python 3.5.

> Are there any obvious functions that we should optimize?

`partion` and `partition_all`: `toolz`-version seems faster than `cytoolz`. That may be because of my test setup but I constantly find that the `toolz` version is slightly faster.

I didn't implement benchmarks for all functions but those I tested seem to perform really well.

**Comment by MSeifert04** [comment]
Thanks for running the benchmarks, this looks really nice!

**Comment by eriknw** [comment]
Thanks for the feedback.  I agree with your expectations and viewing TimSort via `sorted` as the gold standard (and am delighted that `merge_sorted` is comparable to it).  I would add that `heapq` is expected to be slower, because it needs to track which iterable each value comes from due to its data structure, so it compares lists, not values.  The reason it does this is so when values are equal, it chooses the value from the earliest iterable.  We can construct a binary tree that behaves correctly without requiring additional info or comparisons.

btw, the benchmarks shared above were performed using the never-quite-finished-or-released [`benchtoolz`](https://github.com/pytoolz/benchtoolz) package.  I still find `benchtoolz` useful for comparing Cython implementations.

I don't know what's up with `partition` and `partition_all` being slower in `cytoolz`.  I'll take a look.  I found these to be very difficult to improve in Cython.

**Comment by eriknw** [comment]
@MSeifert04, you mentioned `heapq.merge` supporting `reverse=True` in Python 3.5.  Do you think we should add `reverse=` to `merge_sorted` in `toolz`?  `merge_sorted([seq1, seq2], key=lambda x: -x)` won't always be an option depending on the types we are comparing.

**Comment by MSeifert04** [comment]
> I would add that heapq is expected to be slower, because it needs to track which iterable each value comes from due to its data structure, so it compares lists, not values.

You're right, that's something that also slows down my implementation of `merge`. 😏 

> the benchmarks shared above were performed using the never-quite-finished-or-released benchtoolz package

That's a really nice tool, thanks for the link.

> you mentioned heapq.merge supporting reverse=True in Python 3.5. Do you think we should add reverse= to merge_sorted in toolz?

I just mentioned it because of the `key` argument, I have no idea if there is a need for `reverse`.

**Pull request merged**
