### PR TITLE
preliminary debian package work

### PR DESCRIPTION
**Pull request by themusicgod1**
Since cytoolz is required by other software, and since there is an effort to try to get that software into Debian GNU/Linux it would be useful to have the files required to be a debian project synced with this repository. This as a side effect would also help get cytoolz (and software depended upon it) into Ubuntu, Mint, Tails, Devuan, and dozens of other distributions both current and future if successful.  On the Debian side, this effort is tracked in the following Request for Package (RFP): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882725  

I have made a fork and added what seems to be the minimum necessary changes to actually be a Debian package, though since I am not actually a DM/DD/maintainer the name will eventually have to be changed by whoever with the actual credentials required to be a maintainer the Debian project chooses to be the maintainer, but it's a first attempt anyway.  It does build and allows for cytoolz to be installed on a Debian GNU/Linux system.

### CODE REVIEW

**Comment by eriknw** [comment]
Sounds reasonable to me.

**Comment by eriknw** [comment]
My only concern here is whether the recipe you created will become out of date and possibly misleading if more official recipes exist elsewhere.  So, do you expect this recipe to remain up to date, and can we link to other "official" recipes if applicable?

**Comment by themusicgod1** [comment]
That is a valid concern: from the perspective of debian afaik what's going to matter is the 'more official' recipe within debian itself, once cytoolz is uploaded there and passes their checks.  Once that happens, we can sync more closely with that.  But gotta start the ball rolling somewhere. 
Thanks for your prompt response, by the way.

Towards addressing this concern though, I'm going watch this repo (even though I probably wouldn't normally) and will see what I can do about making sure everyone's on the same page.

**Comment by eriknw** [comment]
Great, thanks  Merging!

btw, I plan to release toolz/cytoolz later today.

**Pull request merged**
